/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConversationList: typeof import('./src/components/ConversationList.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    MessageInput: typeof import('./src/components/MessageInput.vue')['default']
    MessageItem: typeof import('./src/components/MessageItem.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
